<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Modelo_provincias extends CI_Model
{

    public $table = 'provincias';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('provincias.id,
                            provincias.nombre');

        $this->db->order_by($this->id, $this->order);return $this->db->get($this->table)->result();
    }

}

/* End of file Contactos_model.php */
/* Location: ./application/models/Contactos_model.php */
/* Please DO NOT modify this information : */
/* Generated by CRUZ Codeigniter CRUD Generator 2021-11-23 17:50:29 */
