<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MAlmacen_historial extends CI_Model
{

    public $table = 'almacen_historial';
    public $id = 'ID';
    public $order = 'DESC';
    // private $fechaIni;
    // private $fechaFin;
    private $limit;

    function __construct()
    {
        parent::__construct();
    }

    private function setWhere($data)
    {
        // $this->fechaIni = $data['fecha_ini'];
        // $this->fechaFin = $data['fecha_fin'];

        // if (!empty($this->fechaIni)) {
        //     $this->db->where($this->table . '.fecha >=', $this->fechaIni . ' 00:00:00');
        // }

        // if (!empty($this->fechaFin)) {
        //     $this->db->where($this->table . '.fecha <=', $this->fechaFin . ' 23:59:59');
        // }
    }

    private function setCommonQuery($data)
    {
        $this->setWhere($data);

        $this->db->from($this->table);
    }

    function getCountBy($data)
    {
        // $this->db->select('almacen_historial.ID');
        $this->setCommonQuery($data);
        return $this->db->count_all_results();
    }

    function getBy($data)
    {
        $this->db->select('almacen_historial.tag,almacen_historial.tipo,almacen_historial.situacion,almacen_historial.fecha,almacen_historial.modo,ID');
        // $this->db->select('log_session.cliente, cliente.nombre as nombre, COUNT(log_session.cliente) AS accesos, MAX(log_session.fecha) AS acceso, ofertas, oferta, pedidos, pedido');

        $this->setCommonQuery($data);
        $this->db->order_by('almacen_historial.fecha', 'DESC');

        if (!empty($data['limit'])) {
            $this->db->limit($data['limit']);
        }
        return $this->db->get()->result();
    }

    // get all
    function get_all()
    {
        $this->db->select('almacen_historial.tag,almacen_historial.tipo,almacen_historial.situacion,almacen_historial.fecha,almacen_historial.modo,ID');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('almacen_historial.tag,almacen_historial.tipo,almacen_historial.situacion,almacen_historial.fecha,almacen_historial.modo,ID');

        if (!empty($q)) {
            $this->db->like('ID', $q);
            $this->db->or_like('almacen_historial.tag', $q);
            $this->db->or_like('almacen_historial.tipo', $q);
            $this->db->or_like('almacen_historial.situacion', $q);
            $this->db->or_like('almacen_historial.fecha', $q);
            $this->db->or_like('almacen_historial.modo', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $oc = '', $od = '')
    {
        $this->db->select('almacen_historial.tag,almacen_historial.tipo,almacen_historial.situacion,almacen_historial.fecha,almacen_historial.modo,ID');


        if (!empty($q)) {
            $this->db->like('almacen_historial.ID', $q);
            $this->db->or_like('almacen_historial.tag', $q);
            $this->db->or_like('almacen_historial.tipo', $q);
            $this->db->or_like('almacen_historial.situacion', $q);
            $this->db->or_like('almacen_historial.fecha', $q);
            $this->db->or_like('almacen_historial.modo', $q);
        }

        if ($oc != '') {
            $this->db->order_by($oc, $od);
        } else
            $this->db->order_by('almacen_historial.fecha', 'desc');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file MAlmacen_historial.php */
/* Location: ./application/models/MAlmacen_historial.php */
/* Please DO NOT modify this information : */
/* Generated by CRUZ Codeigniter CRUD Generator 2021-01-28 13:17:21 */
