<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MContacto_priv extends CI_Model
{

    public $table = 'contactos';
    public $id = 'contacto_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('contactos.contacto_nombre,contactos.contacto_telefono');
        $this->db->order_by($this->id, $this->order);
        // $this->db->join("rol", "contacto.rol_id = rol.rol_id", "left");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('contactos.contacto_nombre,contactos.contacto_telefono');

        // $this->db->join("rol", "contacto.rol_id = rol.rol_id", "left");
        if (!empty($q)) {
            $this->db->like('contacto_id', $q);
            $this->db->or_like('contactos.nombre_contacto', $q);
            $this->db->or_like('contactos.contacto_telefono', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $oc = '', $od = '')
    {
        $this->db->select('contactos.contacto_nombre,contactos.contacto_telefono');


        
        if (!empty($q)) {
            $this->db->like('contacto_id', $q);
            $this->db->or_like('contactos.nombre_contacto', $q);
            $this->db->or_like('contactos.contacto_telefono', $q);
        }

        if ($oc != '') {
            $this->db->order_by($oc, $od);
        } else
            $this->db->order_by('contactos.contacto_id', 'asc');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Mcontacto.php */
/* Location: ./application/models/Mcontacto.php */
/* Please DO NOT modify this information : */
/* Generated by CRUZ Codeigniter CRUD Generator 2020-03-13 10:24:50 */
