<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MGrupo extends CI_Model
{

    public $table = 'grupo';
    public $id = 'grupo_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($solo_activo=FALSE)
    {
        $this->db->select('grupo.nombre,grupo.activo,grupo.orden,grupo_id');
        if($solo_activo) {
            $this->db->where('grupo.activo', 1);
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('grupo.nombre,grupo.activo,grupo.orden,grupo_id');

        if (!empty($q)) {
            $this->db->like('grupo_id', $q);
            $this->db->or_like('grupo.nombre', $q);
            $this->db->or_like('grupo.activo', $q);
            $this->db->or_like('grupo.orden', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $oc = '', $od = '')
    {
        $this->db->select('grupo.nombre,grupo.activo,grupo.orden,grupo_id, (SELECT COUNT(usuario_id) FROM usuario_grupo WHERE usuario_grupo.grupo_id = grupo.grupo_id) as num_usuarios');

        if (!empty($q)) {
            $this->db->like('grupo_id', $q);
            $this->db->or_like('grupo.nombre', $q);
            $this->db->or_like('grupo.activo', $q);
            $this->db->or_like('grupo.orden', $q);
        }

        if ($oc != '') {
            $this->db->order_by($oc, $od);
        } else
            $this->db->order_by('grupo.grupo_id', 'asc');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MGrupo.php */
/* Location: ./application/models/MGrupo.php */
/* Please DO NOT modify this information : */
/* Generated by CRUZ Codeigniter CRUD Generator 2021-01-28 10:28:40 */
