<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MRol extends CI_Model
{

    public $table = 'rol';
    public $id = 'rol_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('rol.nombre,rol.activo,rol.orden,rol_id');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('rol.nombre,rol.activo,rol.orden,rol_id');

        if (!empty($q)) {
            $this->db->like('rol_id', $q);
            $this->db->or_like('rol.nombre', $q);
            $this->db->or_like('rol.activo', $q);
            $this->db->or_like('rol.orden', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $oc = '', $od = '')
    {
        $this->db->select('rol.nombre,rol.activo,rol.orden,rol_id');


        if (!empty($q)) {
            $this->db->like('rol.rol_id', $q);
            $this->db->or_like('rol.nombre', $q);
            $this->db->or_like('rol.activo', $q);
            $this->db->or_like('rol.orden', $q);
        }

        if ($oc != '') {
            $this->db->order_by($oc, $od);
        } else
            $this->db->order_by('orden', 'ASC');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file MRol.php */
/* Location: ./application/models/MRol.php */
/* Please DO NOT modify this information : */
/* Generated by CRUZ Codeigniter CRUD Generator 2020-03-12 11:43:28 */
