<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MUsuario_priv extends CI_Model
{

    public $table = 'usuario';
    public $id = 'usuario_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('usuario.nombre,usuario.apellidos,usuario.email,rol.nombre as rol_id,usuario.rol_id as rol_id_id,usuario.activo,usuario.orden,usuario_id');
        $this->db->order_by($this->id, $this->order);
        $this->db->join("rol", "usuario.rol_id = rol.rol_id", "left");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('usuario.nombre,usuario.apellidos,usuario.email,rol.nombre as rol_id,usuario.rol_id as rol_id_id,usuario.activo,usuario.orden,usuario_id');

        $this->db->join("rol", "usuario.rol_id = rol.rol_id", "left");
        if (!empty($q)) {
            $this->db->like('usuario_id', $q);
            $this->db->or_like('usuario.nombre', $q);
            $this->db->or_like('usuario.apellidos', $q);
            $this->db->or_like('usuario.email', $q);
            $this->db->or_like('rol.nombre', $q);
            $this->db->or_like('usuario.activo', $q);
            $this->db->or_like('usuario.orden', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $oc = '', $od = '')
    {
        $this->db->select('usuario.nombre,usuario.apellidos,usuario.email,rol.nombre as rol_id,usuario.rol_id as rol_id_id,usuario.activo,usuario.orden,usuario_id');


        $this->db->join("rol", "usuario.rol_id = rol.rol_id", "left");
        if (!empty($q)) {
            $this->db->like('usuario.usuario_id', $q);
            $this->db->or_like('usuario.nombre', $q);
            $this->db->or_like('usuario.apellidos', $q);
            $this->db->or_like('usuario.email', $q);
            $this->db->or_like('rol.nombre', $q);
            $this->db->or_like('usuario.activo', $q);
            $this->db->or_like('usuario.orden', $q);
        }

        if ($oc != '') {
            $this->db->order_by($oc, $od);
        } else
            $this->db->order_by('usuario.orden', 'asc');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file MUsuario.php */
/* Location: ./application/models/MUsuario.php */
/* Please DO NOT modify this information : */
/* Generated by CRUZ Codeigniter CRUD Generator 2020-03-13 10:24:50 */
